name : Test of Deployment File

on:
  schedule:
    # Runs "At 11:00 on every day-of-week from Monday through Friday"
    - cron: '*/5 * * * 1-5'
  workflow_dispatch:

jobs:
  build:
    name: Trigger Code Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            ref: main
      # - name: Create report file
      #   run: date +%s > report.txt
      # - name: Creating Release branch
      #   run : |
      #     git config --global push.default current
      #     git checkout -b release-20221226 main
      #     git config --global user.name 'Anuj Sharma'
      #     git config --global user.email 'sanuj8655@gmail.com'
      #     git add .
      #     git commit -am "Automated report"
      #     git push
